---
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
  truthy: disable

ignore:
  - .tox/
  - .venv/
  - .eggs/
  - .git/
  - .mypy_cache/
  - .pytest_cache/
  - .coverage
